# Generated by Django 4.0.2 on 2023-11-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ3'),
        ),
    ]
